### ISSUE TITLE
fumin.rb でエラー

### ISSUE THREAD

**Issue by sasai** [ShigeruIchinoki/taem_c_kadai#23]
fumin.rbのロードで失敗してます。
見たところ、以下のところに問題がありそうです。修正、確認お願いします。
- ダブルクォーテーション(")が全角になっている。
  　5, 88, 90, 92行目
- 89行目の else if 
  Ruby は elsif

**Comment by kkazuma** [comment]
ありがとうございます。
修正しました

**Comment by sasai** [comment]
#25 で修正されているのを確認しました :100:
